# Generated by Django 2.2.28 on 2023-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.BigIntegerField()),
                ('testnam', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
