# Generated by Django 2.2.28 on 2023-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='fdhdghghdf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
