# Generated by Django 2.2.28 on 2023-03-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testname', '0002_tester_fdhdghghdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tester',
            name='fdhdghghdf',
        ),
        migrations.RemoveField(
            model_name='tester',
            name='testnam',
        ),
    ]
