# Generated by Django 2.2.28 on 2023-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testname', '0003_auto_20230330_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='fdhdghghdf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tester',
            name='testnam',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
