# Generated by Django 2.2.28 on 2023-03-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testname', '0004_auto_20230330_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tester',
            name='fdhdghghdf',
        ),
    ]
