# Generated by Django 2.2.28 on 2023-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230330_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ytty',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
