# Generated by Django 2.2.28 on 2023-03-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ytty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ytty',
        ),
    ]
