# Generated by Django 2.2.28 on 2023-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230330_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ytty',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
