# Generated by Django 2.2.28 on 2023-03-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230330_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ytty',
        ),
    ]
